### ISSUE TITLE
Why not publishing a package for snowstorm to npm?

### ISSUE THREAD

**Issue by usirin** [burakcan/react-snowstorm#2]
Instead of manually pulling down the dependency, you can publish it to npm first, so that people who doesn't use `react` can use it as well :)

**Comment by burakcan** [comment]
:+1: will do it tomorrow :)

btw, @usirin napiyon abi yaziyom kodingden falan hic ses etmiyon

**Comment by felix-d** [comment]
FYI The version on npm still has the snowStorm.js error :)
