### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by isaachinman** [burakcan/react-snowstorm#6]
I guess it's that time of year, where clients make stupid requests and such a component becomes necessary.

Line 25 of `lib/index.js` via the npm package reads:

    var _snowStormJs = require('./snowStorm.js')

When, in fact, the file is called `snowstorm.js` (no camel case). Quick fix if anyone still maintains this.

**Comment by burakcan** [comment]
Thank you for reporting @isaachinman . This should be fixed on 0.0.2

**Comment by isaachinman** [comment]
No problem. Happy Christmas.
